LearnDialogue/connexx-chainlink

ChainLink-Client/src/components/EventModal.tsx, ChainLink-Client/src/styles/components/ride-feed-card.css
Link to JIRA ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?selectedIssue=CHAINLINK-14
=> CHAINLINK-14: RSVP List Import

ChainLink-Client/src/components/EventModal.tsx, ChainLink-Client/src/components/ProfileModal.tsx, ChainLink-Client/src/styles/components/profile-modal.css
Added profile modal to event modal ride list. Current version is pretty minimal, just showing some basic user info. Plenty of space to add some basic functionality like the friend request and profile page buttons. 
[CHAINLINK-26](https://heartratehackers.atlassian.net/browse/CHAINLINK-26?atlOrigin=eyJpIjoiODAzYTY2MGNkNzg4NDY2MGFjMzYxNjYyN2I2YTllMWYiLCJwIjoiaiJ9)
=> CHAINLINK-26

ChainLink-Client/src/routes/SignupPage.tsx, ChainLink-Client/src/routes/app/EditProfilePage.tsx, ChainLink-Client/src/routes/app/RidesFeed.tsx, ChainLink-Client/src/styles/edit-profile.css, ChainLink-Client/src/styles/signup.css, ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/graphql/typeDefs.js, ChainLink-Server/models/User.js
Link to JIRA ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?selectedIssue=CHAINLINK-4
=> CHAINLINK-4 Add bike type filtering checkboxes to signup/edit profile UI

ChainLink-Client/src/routes/SignupPage.tsx, ChainLink-Client/src/routes/app/EditProfilePage.tsx, ChainLink-Client/src/routes/app/ProfilePage.tsx, ChainLink-Client/src/styles/profile-page.css, ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/graphql/typeDefs.js, ChainLink-Server/models/User.js
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?selectedIssue=CHAINLINK-16
=> CHAINLINK-16

ChainLink-Client/src/components/EventModal.tsx, ChainLink-Client/src/components/ProfileModal.tsx, ChainLink-Client/src/components/RideFeedCard.tsx, ChainLink-Client/src/components/RsvpButton.tsx, ChainLink-Client/src/graphql/mutations/eventMutations.ts, ChainLink-Client/src/graphql/mutations/userMutations.ts, ChainLink-Client/src/graphql/queries/eventQueries.ts, ChainLink-Client/src/graphql/queries/userQueries.ts, ChainLink-Client/src/routes/ConnectToStravaPage.tsx, ChainLink-Client/src/routes/LoginPage.tsx, ChainLink-Client/src/routes/RedirectPage.tsx, ChainLink-Client/src/routes/ResetPasswordPage.tsx, ChainLink-Client/src/routes/SetNewPasswordPage.tsx, ChainLink-Client/src/routes/SignupPage.tsx, ChainLink-Client/src/routes/app/CreateRide.tsx, ChainLink-Client/src/routes/app/EditProfilePage.tsx, ChainLink-Client/src/routes/app/EditRidePage.tsx, ChainLink-Client/src/routes/app/ProfilePage.tsx, ChainLink-Client/src/routes/app/RidesFeed.tsx
In trying to solve other issues, I noticed duplicate queries. I think centralizing the quires will lead to less code duplicate and confusion.
=> Move graphql quries into central location

ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/graphql/typeDefs.js
Modified server get user query to accept username or user id.
=> get user by id or username

ChainLink-Client/src/main.tsx, ChainLink-Client/src/routes/app/CreateRide.tsx, ChainLink-Client/src/routes/app/EditProfilePage.tsx, ChainLink-Client/src/routes/app/EditRidePage.tsx, ChainLink-Client/src/routes/app/ProfilePage.tsx, ChainLink-Client/src/routes/app/RidesFeed.tsx
Moved nav bar from pages to main.tsx
=> navbar render once

ChainLink-Client/src/components/FriendList.tsx, ChainLink-Client/src/graphql/mutations/friendshipMutations.ts, ChainLink-Client/src/routes/app/ProfilePage.tsx, ChainLink-Client/src/styles/components/friend-list.css, ChainLink-Client/src/styles/profile-page.css, ChainLink-Server/graphql/resolvers/friendship.js, ChainLink-Server/graphql/typeDefs.js
=> Friend list with user info panel

ChainLink-Client/src/components/FriendList.tsx, ChainLink-Client/src/components/UserAvatar.tsx, ChainLink-Client/src/index.css, ChainLink-Client/src/main.tsx, ChainLink-Client/src/routes/ConnectToStravaPage.tsx, ChainLink-Client/src/routes/LoginPage.tsx, ChainLink-Client/src/routes/RedirectPage.tsx, ChainLink-Client/src/routes/SignupPage.tsx, ChainLink-Client/src/routes/app/CreateRide.tsx, ChainLink-Client/src/routes/app/EditProfilePage.tsx, ChainLink-Client/src/styles/profile-page.css, ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/util/email.js, ChainLink-Server/util/error-handling.js
- Refactor app root to only render Navbar when user is logged in
- Add option to UserAvatar to allow it to render a large size (for profiles)
- Configure all buttons to have a hand cursor (pointer) when hovering over them
- Friends list profile list items have hand cursor (pointer) when hovering over them, to indicate they are clickable
- remove majority of console logs
=> Cleanup of various things

ChainLink-Client/src/components/EventModal.tsx, ChainLink-Client/src/components/FriendSelect.tsx, ChainLink-Client/src/components/RideFeedCard.tsx, ChainLink-Client/src/components/ShareRide.tsx, ChainLink-Client/src/featureFlags.ts, ChainLink-Client/src/graphql/mutations/eventMutations.ts, ChainLink-Client/src/styles/components/friend-select.css, ChainLink-Client/src/styles/components/ride-feed-card.css, ChainLink-Client/src/styles/components/share-ride.css, ChainLink-Server/graphql/resolvers/events.js, ChainLink-Server/graphql/typeDefs.js, ChainLink-Server/models/Event.js
https://heartratehackers.atlassian.net/browse/CHAINLINK-63
=> Sharing rides: Chainlink 63

ChainLink-Client/src/components/FriendList.tsx, ChainLink-Client/src/styles/components/friend-list.css, ChainLink-Client/src/styles/profile-page.css
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?assignee=712020%3Ab0b21433-4f3f-477b-9eba-54592ce1b826&selectedIssue=CHAINLINK-50
=> CHAINLINK-50 Changes to Friend List/Request Styling

ChainLink-Client/src/components/EventModal.tsx, ChainLink-Client/src/components/FriendButton.tsx, ChainLink-Client/src/styles/components/event-modal.css, ChainLink-Client/src/styles/components/friend-button.css, ChainLink-Client/src/styles/components/ride-feed-card.css
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?assignee=712020%3Ab0b21433-4f3f-477b-9eba-54592ce1b826&selectedIssue=CHAINLINK-52
=> CHAINLINK-52

ChainLink-Client/src/components/RideList.tsx, ChainLink-Client/src/components/UpcomingRides.tsx, ChainLink-Client/src/graphql/queries/eventQueries.ts, ChainLink-Server/graphql/resolvers/events.js, ChainLink-Server/graphql/typeDefs.js
Link to ticket: https://heartratehackers.atlassian.net/browse/CHAINLINK-62
Desktop:
Mobile:
=> show rides the user has been invited to on their profile page

ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/models/User.js
Link to ticket: https://heartratehackers.atlassian.net/browse/CHAINLINK-65
=> implement 30 min user account lockout after 3 failed login attempts

ChainLink-Client/src/routes/app/CreateRide.tsx
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?assignee=712020%3Ab0b21433-4f3f-477b-9eba-54592ce1b826&selectedIssue=CHAINLINK-61
=> CHAINLINK-61

ChainLink-Client/src/styles/profile-page.css
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?assignee=712020%3Ab0b21433-4f3f-477b-9eba-54592ce1b826&selectedIssue=CHAINLINK-71
=> CHAINLINK-71

ChainLink-Client/src/components/FriendList.tsx, ChainLink-Client/src/styles/components/friend-list.css
Made it so a popup appears when the user attempts to remove a friend that confirms that is what the user wants to do. Everything else regarding the remove friend systems works as is. This feature is feature flagged behind the 'friends' feature by it's inclusion in the friendsList and as such is not individually flagged.
[CHAINLINK-70](https://heartratehackers.atlassian.net/browse/CHAINLINK-70)
=> Added remove friend confirmation.

ChainLink-Client/src/components/Navbar.tsx, ChainLink-Client/src/featureFlags.ts, ChainLink-Client/src/styles/components/navbar.css
Notification Bell in Navbar with different messages for only friend requests, only invites, or both. Red circle+! badge to indicate notification existence. Feature flagged on dev site.
=> NOTIFICATION-BELL

ChainLink-Client/src/components/FriendSelect.tsx, ChainLink-Client/src/components/ShareRide.tsx, ChainLink-Client/src/styles/components/friend-select.css, ChainLink-Client/src/styles/components/share-ride.css
Link to JIRA Ticket: https://heartratehackers.atlassian.net/jira/software/projects/CHAINLINK/boards/1?assignee=712020%3Ab0b21433-4f3f-477b-9eba-54592ce1b826&selectedIssue=CHAINLINK-73
=> CHAINLINK-73

ChainLink-Client/src/routes/app/CreateRide.tsx
Fixed console error in auto-rsvp ride creation
=> CONSOLE ERROR RESOLUTION - RSVP

ChainLink-Client/src/routes/SignupPage.tsx, ChainLink-Client/src/routes/app/RidesFeed.tsx
=> Chainlink 77

ChainLink-Client/src/components/ProfilePic.tsx, ChainLink-Client/src/components/UserAvatar.tsx
https://heartratehackers.atlassian.net/browse/CHAINLINK-74
=> add file sanitation. split prod and dev buckets for security

ChainLink-Client/.eslintrc.cjs, ChainLink-Client/package.json
Added npm package that fixes vitest unit tests from failing due to nonexistent imports
=> Update ESLint configuration and add testing library dependency

ChainLink-Client/src/components/ProfilePic.tsx, ChainLink-Server/graphql/resolvers/index.js, ChainLink-Server/graphql/resolvers/users.js, ChainLink-Server/graphql/typeDefs.js
Fixed: 
- Birthday calculation in UI 
- Birthday being converted to a day ahead due to timezone issues
=> Fixed birthday timezone issue and age UI calculation
